#pragma once

#define IDI_IBSTART 101
#define IDI_ACTION_ENTERPRISE 201
#define IDI_ACTION_DESIGNER 202
#define IDI_ACTION_EDIT 203
#define IDI_ACTION_CACHE 204
#define IDI_ACTION_SHORTCUT 205
#define IDI_ACTION_DELETE 206
#define IDI_ACTION_ADD 207
#define IDI_TREE_FOLDER 208
#define IDI_TREE_DATABASE 209
#define IDI_ACTION_FAVORITE 210
#define IDI_ACTION_REFRESH 211
#define IDI_TREE_FILE_DATABASE 212
#define IDI_TREE_SERVER_DATABASE 213
